  
runtime: python27
#env: flex
api_version: 1
threadsafe: true

handlers:
- url: /.*

  script: myrepolib.repomod.app
#libraries:
#- name: flask
 # version: 0.12
skip_files:
- .git
#- .venv
- venv 
- logs/